version: '3'
services:
  db:
    image: postgres:13.4-alpine
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
volumes:
  postgres-vol:
